# deploy monitoring services for proxmox (nodes, lxc, vms) with influxdb and grafana

services:
  influxdb:
    container_name: influxdb
    image: influxdb:2
    ports:
      - '8086:8086' # puerto web
    volumes:
      - influxdb-storage:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    networks:
      - grafana-monitoring
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:main-ubuntu
    user: "0"
    ports:
      - '4000:3000' # puerto web
    networks:
      - grafana-monitoring
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

  telegraf:
    container_name: telegraf
    image: telegraf:latest
    user: telegraf:988
    networks:
      - grafana-monitoring
    volumes:
      - '/home/krosis/docker-compose/grafana-monitoring/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro' #config file
      - '/:/hostfs:ro' # to monitor docker-vm
      - '/var/run/docker.sock:/var/run/docker.sock' # to monitor docker containers
    restart: unless-stopped
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9080:9090
    volumes:
      - '/home/krosis/docker-compose/grafana-monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml' #config file
      - prometheus-storage:/prometheus #persistent storage
    networks:
      - grafana-monitoring
    restart: unless-stopped

  # speedtest: optional
  speedtest-exporter:
    image: miguelndecarvalho/speedtest-exporter
    container_name: speedtest-exporter
    ports:
      - 9798:9798
    networks:
      - grafana-monitoring
    restart: unless-stopped

volumes:
  influxdb-storage:
  influxdb-config:
  grafana-storage:
  prometheus-storage:

networks:
  grafana-monitoring:
