# Deployment of Backrest (restic wrapper) for backups on remote NFS share or SMB share.
services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    restart: unless-stopped
    ports:
      - 9898:9898
    volumes:
      - ./data:/data
      - ./config:/config
      - ./cache:/cache
      - "/var/lib/docker/volumes:/noveria-docker-volumes:ro" # [optional] mount local paths to backup here.
      - "/mnt/docker-volumes/backups:/docker-repo:rw" # [optional] mount repos if using local storage, not necessary for remotes e.g. B3, S3, etc.
    environment:
      - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
      - TZ=America/Bogota # set the timezone for the container, used as the timezone for cron jobs.
