---
- name: Install qemu-guest-agent for KVM
  apt:
    name: qemu-guest-agent
    state: present
    update_cache: yes

- name: Start service qemu-guest-agent
  systemd:
    name: qemu-guest-agent
    state: started
    enabled: yes
