# Deployment of grafana setup monitoring & influxdb for collecting

- name: Setup Grafana directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/docker-compose/grafana-monitoring"
    state: directory
    mode: '0755'  # Optional file permissions
    owner: krosis  # Optional ownership
    group: krosis  # Optional group ownership

- name: Deploy Grafana with Docker-compose
  ansible.builtin.template:
    src: "templates/docker_compose.yml"
    dest: "{{ lookup('env', 'HOME') }}/docker-compose/grafana-monitoring/docker-compose.yaml"
    mode: '0755'  # Optional file permissions
    owner: krosis  # Optional ownership
    group: krosis  # Optional group ownership

- name: Run Grafana docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ lookup('env', 'HOME') }}/docker-compose/grafana-monitoring"
