# Deployment of Restic for Docker volumes backup on remote NFS share or SMB share.
# Use 3 containers: one for creating backups and restore, one for removing/prune backups and one for checking backups integrity
# is one checking failed it will alert the backups to be made on schedule.
services:
  backup:
    image: mazzolino/restic
    container_name: restic-backup
    hostname: restic
    environment:
      RUN_ON_STARTUP: "true" #change as you wish
      BACKUP_CRON: "0 */12 * * *" #this is twice daily, i.e., every 12 hours
      RESTIC_REPOSITORY: /restic
      RESTIC_PASSWORD: MY_SUPER_LONG_PASSWORD
      RESTIC_BACKUP_SOURCES: /mnt/docker-volumes
      RESTIC_COMPRESSION: auto
      RESTIC_BACKUP_ARGS: >-
        --tag restic-noveria #add tags, whatever you need to mark backups
        --verbose
      RESTIC_FORGET_ARGS: >- #change as required
        --keep-last 10
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
      TZ: America/Bogota
    volumes:
      - /mnt/docker-volumes/backups:/restic #change the left hand side to where you want to store the backups. As you can see I'm storing it on my NAS that is mounted to the host /home/truenas
      - /mnt/docker-volumes/backups/tmp-for-restore:/tmp-for-restore #USE THIS FOLDER FOR RESTORE - CAN VIEW EACH CONTAINER
      - /home/ubuntu/docker:/mnt/volumes:ro
    security_opt:
      - no-new-privileges:true

  prune:
    image: mazzolino/restic
    container_name: restic-prune
    hostname: restic-prune
    environment:
      RUN_ON_STARTUP: "true"
      PRUNE_CRON: "0 0 4 * * *"
      RESTIC_REPOSITORY: /restic
      RESTIC_PASSWORD: USE_SAME_PASSWORD_AS_ABOVE
      TZ: America/Bogota
    security_opt:
      - no-new-privileges:true

  check:
    image: mazzolino/restic
    container_name: restic-check
    hostname: restic-check
    environment:
      RUN_ON_STARTUP: "false"
      CHECK_CRON: "0 15 5 * * *"
      RESTIC_CHECK_ARGS: >-
        --read-data-subset=10%
      RESTIC_REPOSITORY: /restic
      RESTIC_PASSWORD: USE_SAME_PASSWORD_AS_ABOVE
      TZ: America/Bogota
    security_opt:
      - no-new-privileges:true
