# deploy excalidraw
services:
  excalidraw:
    container_name: excalidraw
    image: excalidraw/excalidraw:latest
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.excalidraw.entrypoints=http"
      - "traefik.http.routers.excalidraw.rule=Host(`draw.homelab.blastwave.xyz`)"
      - "traefik.http.middlewares.excalidraw-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.excalidraw.middlewares=excalidraw-https-redirect"
      - "traefik.http.routers.excalidraw-secure.entrypoints=https"
      - "traefik.http.routers.excalidraw-secure.rule=Host(`draw.homelab.blastwave.xyz`)"
      - "traefik.http.routers.excalidraw-secure.tls=true"
      - "traefik.http.routers.excalidraw-secure.service=excalidraw"
      - "traefik.http.services.excalidraw.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
