# deploy excalidraw
services:
  excalidraw:
    container_name: excalidraw
    image: excalidraw/excalidraw:latest
    networks:
      - proxy
    labels:
      - "traefik.enable=true"

networks:
  proxy:
    external: true
