pageInfo:
  title: Firelink-Shrine
  description: Bienvenido al Maleborge!
  navLinks:
    - title: GitHub
      path: https://github.com/sirArthurDayne
    - title: Documentation
      path: https://dashy.to/docs
appConfig:
  theme: one-dark
  layout: horizontal
  iconSize: medium
sections:
  - name: Monitoreo
    icon: fa-monitor
    displayData:
      sortBy: default
      rows: 4
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - &ref_0
        title: Grafana
        description: grafana dashboard
        icon: hl-grafana
        url: https://monitor.homelab.blastwave.xyz/
        target: newtab
        id: 0_956_grafana
      - &ref_1
        title: Gotify
        description: alertas del sistema
        icon: hl-gotify
        url: https://gotify.homelab.blastwave.xyz/#/
        target: newtab
        id: 1_956_gotify
      - &ref_2
        title: Prometheus
        description: dashboard de prometheus
        icon: hl-prometheus
        url: http://noveria.blastwave.lab:9080/
        target: newtab
        id: 2_956_prometheus
      - &ref_3
        title: influxdb
        description: cliente influxdb
        icon: hl-influxdb
        url: http://noveria.blastwave.lab:8086/
        target: newtab
        id: 3_956_influxdb
      - &ref_4
        title: Traefik
        description: traefik dashboard
        icon: hl-traefik
        url: https://traefik-dashboard.homelab.blastwave.xyz/
        target: newtab
        id: 4_956_traefik
    filteredItems:
      - *ref_0
      - *ref_1
      - *ref_2
      - *ref_3
      - *ref_4
  - name: Proxmox
    icon: hl-proxmox
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - &ref_5
        title: Proxmox
        description: Proxmox Citadel dashboard
        icon: hl-proxmox
        url: https://pve.homelab.blastwave.xyz/
        target: newtab
        id: 0_765_proxmox
    filteredItems:
      - *ref_5
  - name: Redes-Casa
    icon: fa-network
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - &ref_6
        title: OPNsense
        description: opnsense
        icon: hl-opnsense
        url: https://rtnormandy.blastwave.lab/
        target: newtab
        id: 0_920_opnsense
      - &ref_7
        title: APNormandy
        description: dashboard access point
        icon: hl-grandstream
        url: https://apnormandy.blastwave.lab/overview/index
        target: newtab
        id: 1_920_apnormandy
      - &ref_8
        title: TPLink Switch
        description: switch tplink
        icon: hl-tplink
        url: http://swnormandy.blastwave.lab/
        target: newtab
        id: 2_920_tplinkswitch
      - &ref_9
        title: NETGEAR switch
        description: dashboard switch netgear
        icon: hl-netgear
        url: http://swnormandy2.blastwave.lab/
        target: newtab
        id: 3_920_netgearswitch
      - &ref_10
        title: Adguard
        description: DNS filter dashboard
        icon: hl-adguard-home
        url: http://10.10.0.1:3000/
        target: newtab
        id: 4_920_adguard
    filteredItems:
      - *ref_6
      - *ref_7
      - *ref_8
      - *ref_9
      - *ref_10
  - name: Docker-Services
    icon: fa-docker
    displayData:
      sortBy: default
      rows: 4
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - &ref_10
        title: Portainer
        description: Portainer Dashboard
        icon: hl-portainer
        url: https://portainer.homelab.blastwave.xyz/
        target: newtab
        id: 0_1481_portainer
      - &ref_11
        title: Dashy
        description: Dashboard
        icon: hl-dashy
        url: http://noveria.blastwave.lab:8090/
        target: newtab
        id: 1_1481_dashy
      - &ref_12
        title: EmulatorJS
        description: Emulator Menu
        icon: hl-emulatorjs
        url: http://10.10.0.115:9090/
        target: newtab
        id: 2_1481_emulatorjs
      - &ref_13
        title: Emulatorjs-config
        description: config emulatorjs
        icon: hl-emulatorjs
        url: http://10.10.0.115:3420/
        target: newtab
        id: 3_1481_emulatorjsconfig
      - &ref_14
        title: netboot.xyz
        description: netboot dashboard
        icon: hl-netbootxyz
        url: http://10.10.0.115:3000/
        target: newtab
        id: 4_1481_netbootxyz
    filteredItems:
      - *ref_10
      - *ref_11
      - *ref_12
      - *ref_13
      - *ref_14
  - name: NAS
    icon: fa-nas
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - &ref_15
        title: NAS
        description: NAS
        icon: hl-cockpit
        url: https://10.10.0.120:9090/system
        target: newtab
        id: 0_226_nas
    filteredItems:
      - *ref_15
  - name: Tools
    icon: fa-tools
    displayData:
      sortBy: default
      rows: 3
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - &ref_16
        title: ChatGPT
        description: chatgpt.com
        icon: hl-openai-light
        url: https://chatgpt.com
        target: newtab
        id: 0_529_chatgpt
      - &ref_17
        title: Keeper
        description: keeper vault
        icon: hl-bitwarden
        url: https://keepersecurity.com/vault/
        target: newtab
        id: 1_529_keeper
      - &ref_18
        title: Cloudflare
        description: cloudlare dashboard
        icon: hl-cloudflare
        url: https://dash.cloudflare.com/
        target: newtab
        id: 2_529_cloudflare
    filteredItems:
      - *ref_16
      - *ref_17
      - *ref_18

